name: visualise_blood_pressure
description: "Visualise Blood Pressure Reading."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # path_provider: ^2.1.5
  # path: ^1.9.0
  flutter_inappwebview: ^6.1.5

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/docs/
    - assets/docs/static/
    - assets/docs/static/css/
    - assets/docs/static/js/
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.14.1"

flutter_launcher_icons:
  # run with: flutter pub run flutter_launcher_icons
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/icons/icon.png"
  image_path_ios: "assets/icons/icon.png"
  android: "ic_launcher" # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
  adaptive_icon_foreground: "assets/icons/icon.png"
  adaptive_icon_background: "#ffffff"

  
  web:
    generate: true
    image_path: "assets/icons/icon.png"
    background_color: "##b68800"
    theme_color: "##b68800"
  windows:
    generate: true
    image_path: "assets/icons/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/icon.png"